name: Upload APK artifact

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'  # use latest stable

      # Cache dependencies (faster builds)
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      # Install dependencies
      - run: flutter pub get

      # Analyze code
      - run:  flutter analyze || true

      # Run tests
      - run: flutter test

      # Build APK
      - run: flutter build apk --release

      # Upload APK for download
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk